package com.example.bean;

import org.hibernate.annotations.Proxy;

import javax.persistence.*;
import java.util.Date;

/**
 * Annotated Variant Calling Format (VCF) uploaded by the users
 * TODO: Matched content
 *
 * @author Jie Jin
 * @author Zhejian YU
 */
@Proxy(lazy = false)
@Entity
@Table(name = "sample")
public class Sample {
	@Id @GeneratedValue(strategy = GenerationType.IDENTITY) @Column(name = "id")
	private long id;
	@Column(name = "created_at")
	private Date createdAt;
	@Column(name = "user_name", length = 100, nullable=false)
	private String userName;
	@Column(name = "matched_id", length = 100, nullable=false)
	private String matchedId;
	@OneToOne(targetEntity = DrugLabel.class, cascade = CascadeType.ALL)
	private DrugLabel matchedDrug;

	public Sample() {}

	/**
	 * Constructor for Annotated Variant Calling Format (VCF) uploaded by the users.
	 * Each match will produce multiple records
	 *
	 * @param id Index of the sample, generated by the database
	 * @param createdAt Date it was uploaded
	 * @param userName By whom it was uploaded. See also: {@link RegisteredUser}
	 * @param matchedId Matched drug IDs in one time. See also: {@link Drug}
	 */
	public Sample(Long id, Date createdAt, String userName, String matchedId) {
		this.id = id;
		this.createdAt = createdAt;
		this.userName = userName;
		this.matchedId = matchedId;
	}

	public Date getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMatchedId() {
		return matchedId;
	}

	public void setMatchedId(String macthedId) {
		this.matchedId = macthedId;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public DrugLabel getMatchedDrug() {
		return matchedDrug;
	}

	public void setMatchedDrug(DrugLabel matchedDrug) {
		this.matchedDrug = matchedDrug;
	}
}
